# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca625cccca332f7f4ad8b84edefb8d5987257a2f96adadd766e68502fbf3586fc2dfb9095a19d65640e4c80e0947a0bf4596edfd0d16c330be96308899bbf67e

test:
  secret_key_base: 38ff310fac624e357837d20801b0cb33676da10fd530ef67053d35769285c4f77e9c16127efc0b020c0a70c78a187727508c22dfea14d9ace76c5686f65be8a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
